#!/root/walless_venv/bin/python3

import json
from walless_utils import db, setup_everything, cfg


def main():
    setup_everything()
    all_nodes = db.all_servers()
    all_nodes.sort(key=lambda n: 'hidden' in n.tag)
    configs = list()
    for node in all_nodes:
        if 'no_monitor' in node.properties or (node.ipv4 is None and node.ipv6 is None):
            continue
        name = node.name.split()[0] + f' [{node.node_id}]'
        configs.append({
            'username': node.uuid,
            'name': name,
            'type': node.ipv4,
            'host': node.ipv4,
            'location': node.idc,
            'password': cfg['status']['password']
        })
    json.dump({"servers": configs}, open('server/config.json', 'w'), indent=2)


if __name__ == '__main__':
    main()
